---
# tasks file for jmeter
# 必要なパッケージのインストール
- name: install packages
  yum:
    name:
      - httpd
      - wget
      - zip
      - unzip
      - java-1.8.0-openjdk.x86_64
      - java-1.8.0-openjdk-devel.x86_64
      - jq

- name: confirm stat jmeter_binary
  stat: 
    path: /usr/local/jmeter
  register: result_jmeter

# Jmeterのインストール
- name: get jmeter
  unarchive:
    src: https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.zip
    dest: /usr/local/
    remote_src: yes
  when: not result_jmeter.stat.exists

- name: confirm stat jmeter_orgdir
  stat: 
    path: /usr/local/apache-jmeter-5.4
  register: result_jmeter_org

# Jmeterのリネーム
- name: rename jmeter_dir
  shell: mv apache-jmeter-5.4 jmeter
    chdir=/usr/local/
  ignore_errors: yes
  when: result_jmeter_org.stat.exists

# Jmeter起動用のシェルスクリプトを設置
- name: put start-controller_cui.sh
  copy:
    src: ../files/start-controller_cui.sh
    dest: /usr/local/jmeter/bin/start-controller_cui.sh
    owner: root
    group: root
    mode: 0755
    backup: yes

# Jmeter設定ファイルを設置
- name: put jmeter.properties
  copy:
    src: ../files/jmeter.properties
    dest: /usr/local/jmeter/bin/jmeter.properties
    owner: root
    group: root
    mode: 0644
    backup: yes

# Jmeterのssl通信を無効化
- name: change user.properties
  lineinfile:
    dest: /usr/local/jmeter/bin/user.properties
    regexp: "#server.rmi.ssl.disable=false"
    line: "server.rmi.ssl.disable=true"
    backup: yes

# HEAPメモリのサイズを調整
- name: change HEAP_SIZE
  replace:
    dest: /usr/local/jmeter/bin/jmeter
    regexp: '\DHEAP:="-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m"}"'
    replace: 'HEAP:="-Xms{{ heapm_size }} -Xmx{{ heapm_size }} -XX:MaxMetaspaceSize={{ heapm_size }}"}"'
    backup: yes

# apacheの起動
- name: start apache
  systemd:
    name: httpd
    state: started
    enabled: yes
