---
# tasks file for tigervnc
# GUI環境パッケージのインストール
- name: install vnc
  yum:
    name:
      - tigervnc-server
      - expect
    state: present

- name: install gui-env
  shell: yum groupinstall "GNOME Desktop" -y

# firewalldを無効化
- name: disable_firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes

# VNCのパスワードを設定
- name: define vncuser-passwd
  become: yes
  become_user: root
  script: ../files/vncpasswd.sh

# VNCの設定ファイルの設置
- name: put vncserver@.service
  copy:
    src: ../files/vncserver@.service_root
    dest: /etc/systemd/system/vncserver@:1.service
    owner: root
    group: root
    mode: 0644

# VNCSERVERの再起動
- name: restart vncserver
  systemd:
    name: vncserver@:1.service
    state: started
    daemon_reload: yes
    enabled: yes
