---
# tasks file for tigervnc

# tigervnc-server インストール
- name: install vnc
  yum:
    name:
      - tigervnc-server
      - expect
      - epel-release
    state: present

- name: install python-pip
  yum:
    name:
      - python-pip
    state: present
  when:
    - ansible_facts['distribution_major_version'] == "7" or ansible_facts['distribution_major_version'] == "9"

- name: pip install pexpect
  pip:
    name:
      - pexpect

# GUI 関連 パッケージ インストール ( RHEL7 )
- name: install GNOME Desktop for GUI ENV RHEL7
  shell: yum groupinstall "GNOME Desktop" -y --setopt=group_package_types=mandatory,default,optional
  when:
    - ansible_facts['distribution_major_version'] == "7"

# GUI 関連 パッケージ インストール ( RHEL8 or RHEL9 )
- name: install GNOME Desktop for GUI ENV RHEL8 or RHEL9
  shell: dnf groupinstall "Server with GUI" -y
  when:
    - ansible_facts['distribution_major_version'] == "8" or ansible_facts['distribution_major_version'] == "9"

# firewalld 無効化
- name: disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes

# vncpasswd
- name: vncpasswd
  expect:
    command: vncpasswd
    responses:
      "Password:": "{{ vnc_passwd | default('vncserver', true) }}"
      "Verify:": "{{ vnc_passwd | default('vncserver', true) }}"
      "Would you like to enter a view-only password (y/n)?": "n\r"

# VNC Unit ファイル 設置
- name: deploy vncserver@.service Unit file
  copy:
    src: ../files/vncserver@.service_root
    dest: /etc/systemd/system/vncserver@:1.service
    owner: root
    group: root
    mode: 0644

# VNC 起動
- name: start vncserver
  systemd:
    name: vncserver@:1.service
    state: started
    daemon_reload: yes
    enabled: yes
