---
# tasks file for tigervnc

# tigervnc-server のインストール
- name: install vnc
  yum:
    name:
      - tigervnc-server
      - expect
    state: present

# GUI 周りのパッケージをインストール
- name: install GNOME Desktop for GUI ENV
  shell: yum groupinstall "GNOME Desktop" -y --setopt=group_package_types=mandatory,default,optional

# firewalld を無効化
- name: disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes

# VNC パスワード設定スクリプトを実行
- name: run vncpasswd.sh script for define password
  become: yes
  become_user: root
  script: ../files/vncpasswd.sh

# VNC 設定ファイルの設置
- name: deploy vncserver@.service Unit file
  copy:
    src: ../files/vncserver@.service_root
    dest: /etc/systemd/system/vncserver@:1.service
    owner: root
    group: root
    mode: 0644

# VNC 起動
- name: start vncserver
  systemd:
    name: vncserver@:1.service
    state: started
    daemon_reload: yes
    enabled: yes
