---
- include_tasks: apache.yml
- include_tasks: php-fpm.yml

- name: git clone flanker
  ansible.builtin.git:
    repo: https://github.com/snkk1210/flanker.git
    dest: /var/www/vhosts/management.local

- name: chown apache:apache /var/www/vhosts/management.local/public
  file:
    path: "/var/www/vhosts/management.local/public"
    state: directory
    owner: apache
    group: apache
    mode: 02775

- name: chown apache:apache /var/www/html
  file:
    path: "/var/www/html"
    state: directory
    owner: apache
    group: apache
    mode: 0755