---
# yum update
- name: yum update
  yum:
    name: "*"
    state: latest

# Development tools の導入
- name: yum groupinstall Development tools
  yum:
    name: "@Development tools"
    state: latest

# epel インストール
- name: install epel-release
  yum:
    name: epel-release

# selinux ライブラリをインストール
- name: install libselinux-python
  yum:
    name: libselinux-python
    state: present
  ignore_errors: yes

# selinux を無効化
- name: disable selinux
  selinux:
    state: disabled

# firewalld を無効化
- name: disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes

# 追加パッケージを導入
- name: install common packages
  yum:
    name:
      - net-tools
      - nmap
      - mailx
      - vim
      - bind-utils
      - telnet
      - dstat
      - unzip
      - zip
      - etckeeper
    state: present

# hostname 変更
- name: change hostname
  hostname: name="{{ inventory_hostname }}"

# sysctl 変更
- name: optimize kernel parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: 'net.core.somaxconn',value: '1024' }
    - { name: 'net.core.netdev_max_backlog',value: '5000' }
    - { name: 'net.core.rmem_max',value: '16777216' }
    - { name: 'net.core.wmem_max',value: '16777216' }
    - { name: 'net.ipv4.tcp_wmem',value: '4096 12582912 16777216' }
    - { name: 'net.ipv4.tcp_rmem',value: '4096 12582912 16777216' }
    - { name: 'net.ipv4.tcp_max_syn_backlog',value: '8096' }
    - { name: 'net.ipv4.tcp_slow_start_after_idle',value: '0' }
    - { name: 'net.ipv4.tcp_tw_reuse',value: '1' }
    - { name: 'net.ipv4.ip_local_port_range',value: '10240 65535' }
    - { name: 'vm.swappiness',value: '10' }

# limits_conf 変更
- name: optimize ulimit
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: nofile
    value: 65536
  with_items:
    - { domain: 'root' ,limit_type: 'soft' }
    - { domain: 'root' ,limit_type: 'hard' }
    - { domain: '*' ,limit_type: 'soft' }
    - { domain: '*' ,limit_type: 'hard' }

# timezone 変更
- name: change timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

# history 時刻表示追加
- name: modify /root/.bashrc to add HISTTIMEFORMAT
  lineinfile:
     dest=/root/.bashrc
     line="HISTTIMEFORMAT='%Y-%m-%dT%T%z '"

- include: host_change.yml
- include: etckeeper_commit.yml