---
# tasks file for slave-jmeter
# JMeterノード 起動スクリプトを設置
- name: deploy jmeter-server.sh script
  copy:
    src: ../files/jmeter-server.sh
    dest: /usr/local/jmeter/bin/jmeter-server.sh
    owner: root
    group: root
    mode: 0755

# JMeter worker Unit ファイルを設置
- name: deploy jmeter-worker.service Unit file
  copy:
    src: ../files/jmeter-worker.service
    dest: /etc/systemd/system/jmeter-worker.service
    owner: root
    group: root
    mode: 0644

# JMeter worker 設定変更 ( eth0 参照 )
- name: change config jmeter-server eth0
  blockinfile:
    dest: /usr/local/jmeter/bin/jmeter-server
    insertafter: '^#RMI_HOST_DEF=-Djava.rmi.server.hostname=xxx.xxx.xxx.xxx'
    content: RMI_HOST_DEF=-Djava.rmi.server.hostname={{ ansible_eth0.ipv4.address }}
    backup: yes
  when: ansible_eth0.ipv4.address is defined 

# JMeter worker 設定変更 ( eth1 参照 )
- name: change config jmeter-server eth1
  blockinfile:
    dest: /usr/local/jmeter/bin/jmeter-server
    insertafter: '^#RMI_HOST_DEF=-Djava.rmi.server.hostname=xxx.xxx.xxx.xxx'
    content: RMI_HOST_DEF=-Djava.rmi.server.hostname={{ ansible_eth1.ipv4.address }}
    backup: yes
  when: ansible_eth1.ipv4.address is defined

# JMeter worker 設定変更 ( ens5 参照 )
- name: change config jmeter-server ens5
  blockinfile:
    dest: /usr/local/jmeter/bin/jmeter-server
    insertafter: '^#RMI_HOST_DEF=-Djava.rmi.server.hostname=xxx.xxx.xxx.xxx'
    content: RMI_HOST_DEF=-Djava.rmi.server.hostname={{ ansible_ens5.ipv4.address }}
    backup: yes
  when: ansible_ens5.ipv4.address is defined

# JMeter worker 設定変更 ( enp0s8 参照 )
- name: change config jmeter-server enp0s8
  blockinfile:
    dest: /usr/local/jmeter/bin/jmeter-server
    insertafter: '^#RMI_HOST_DEF=-Djava.rmi.server.hostname=xxx.xxx.xxx.xxx'
    content: RMI_HOST_DEF=-Djava.rmi.server.hostname={{ ansible_enp0s8.ipv4.address }}
    backup: yes
  when: ansible_enp0s8.ipv4.address is defined

# JMeter worker サービス起動
- name: start jmeter-worker.service
  systemd:
    name: jmeter-worker.service
    state: started
    daemon_reload: yes
    enabled: yes
