---
# tasks file for slave
# jmeterノード起動スクリプト設置
- name: put jmeter-server.sh
  copy:
    src: ../files/jmeter-server.sh
    dest: /usr/local/jmeter/bin/jmeter-server.sh
    owner: root
    group: root
    mode: 0755

# Jmeterノードサービス化
- name: put jmeter-client.service
  copy:
    src: ../files/jmeter-client.service
    dest: /etc/systemd/system/jmeter-client.service
    owner: root
    group: root
    mode: 0644

# Jmeterノード設定変更(eth0 参照)
- name: change jmeter-server
  blockinfile:
    dest: /usr/local/jmeter/bin/jmeter-server
    insertafter: '^#RMI_HOST_DEF=-Djava.rmi.server.hostname=xxx.xxx.xxx.xxx'
    content: RMI_HOST_DEF=-Djava.rmi.server.hostname={{ ansible_eth0.ipv4.address }}
    backup: yes
  when: eth0 is defined

# Jmeterノード設定変更(eth1 参照)
- name: change jmeter-server
  blockinfile:
    dest: /usr/local/jmeter/bin/jmeter-server
    insertafter: '^#RMI_HOST_DEF=-Djava.rmi.server.hostname=xxx.xxx.xxx.xxx'
    content: RMI_HOST_DEF=-Djava.rmi.server.hostname={{ ansible_eth1.ipv4.address }}
    backup: yes
  when: eth0 is undefined

# Jmeterノードサービス起動
- name: start jmeter-client.service
  systemd:
    name: jmeter-client.service
    state: started
    daemon_reload: yes
    enabled: yes
