---
php_modules:
  - "php"
  - "php-fpm"
  - "php-cli"
  - "php-devel"
  - "php-common"
  - "php-json"
  - "php-soap"
  - "php-xml"
  - "php-mbstring"
  - "php-mcrypt"
  - "php-pdo"
  - "php-gd"
  - "php-process"
  - "php-intl"
  - "php-pecl-apcu"
  - "php-mysql"
  - "php-opcache"
